export const BLOG_REQUEST = "BLOG_REQUEST";
export const BLOG_SUCCESS = "BLOG_SUCCESS";
export const BLOG_FAIL  = "BLOG_FAIL";

export const BLOG_CAT_REQUEST = "BLOG_CAT_REQUEST";
export const BLOG_CAT_SUCCESS = "BLOG_CAT_SUCCESS";
export const BLOG_CAT_FAIL  = "BLOG_CAT_FAIL";

export const SINGLEBLOG_REQUEST = "SINGLEBLOG_REQUEST";
export const SINGLEBLOG_SUCCESS = "SINGLEBLOG_SUCCESS";
export const SINGLEBLOG_FAIL  = "SINGLEBLOG_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS"