export const BLOG_REQUEST = "BLOG_REQUEST";
export const BLOG_SUCCESS = "BLOG_SUCCESS";
export const BLOG_FAIL  = "BLOG_FAIL";

export const BLOG_CAT_REQUEST = "BLOG_CAT_REQUEST";
export const BLOG_CAT_SUCCESS = "BLOG_CAT_SUCCESS";
export const BLOG_CAT_FAIL  = "BLOG_CAT_FAIL";

export const SINGLE_BLOG_REQUEST = "SINGLE_BLOG_REQUEST";
export const SINGLE_BLOG_SUCCESS = "SINGLE_BLOG_SUCCESS";
export const SINGLE_BLOG_FAIL  = "SINGLE_BLOG_FAIL";

export const RELATED_BLOG_REQUEST = "RELATED_BLOG_REQUEST";
export const RELATED_BLOG_SUCCESS = "RELATED_BLOG_SUCCESS";
export const RELATED_BLOG_FAIL  = "RELATED_BLOG_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS"