export const SELECTED_CITY = "SELECETD_CITY"
export const SELECTED_LOCALITY = "SELECTED_LOCALITY"
export const HEADER_SEARCH ="HEADER_SEARCH"

export const LISTCITY_REQUEST ="LISTCITY_REQUEST"
export const LISTCITY_SUCCESS ="LISTCITY_SUCCESS"
export const LISTCITY_FAIL ="LISTCITY_FAIL"

export const LISTLOCALITY_REQUEST ="LISTLOCALITY_REQUEST"
export const LISTLOCALITY_SUCCESS ="LISTLOCALITY_SUCCESS"
export const LISTLOCALITY_FAIL ="LISTLOCALITY_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS";