export const LOCALITY_BANNER_REQUEST = "LOCALITY_BANNER_REQUEST"
export const LOCALITY_BANNER_SUCCESS = "LOCALITY_BANNER_SUCCESS"
export const LOCALITY_BANNER_FAIL = "LOCALITY_BANNER_FAIL"

export const ALL_CAT_REQUEST = "ALL_CAT_REQUEST";
export const ALL_CAT_SUCCESS = "ALL_CAT_SUCCESS";
export const ALL_CAT_FAIL  = "ALL_CAT_FAIL";

export const DAY_OFFER_REQUEST = "DAY_OFFER_REQUEST";
export const DAY_OFFER_SUCCESS = "DAY_OFFER_SUCCESS";
export const DAY_OFFER_FAIL  = "DAY_OFFER_FAIL";

export const HOME_STORE_REQUEST = "HOME_STORE_REQUEST";
export const HOME_STORE_SUCCESS = "HOME_STORE_SUCCESS";
export const HOME_STORE_FAIL  = "HOME_STORE_FAIL";

export const HOME_NEWSTORE_REQUEST = "HOME_NEWSTORE_REQUEST";
export const HOME_NEWSTORE_SUCCESS = "HOME_NEWSTORE_SUCCESS";
export const HOME_NEWSTORE_FAIL  = "HOME_NEWSTORE_FAIL";

export const HBLOG_REQUEST = "HBLOG_REQUEST";
export const HBLOG_SUCCESS = "HBLOG_SUCCESS";
export const HBLOG_FAIL  = "HBLOG_FAIL";


export const CLEAR_ERROR = "CLEAR_ERROR"