export const ALL_OFFER_REQUEST = "ALL_STORE_REQUEST";
export const ALL_OFFER_SUCCESS = "ALL_STORE_SUCCESS";
export const ALL_OFFER_FAIL  = "ALL_STORE_FAIL";



export const LISTING_CAT_REQUEST = "LISTING_CAT_REQUEST";
export const LISTING_CAT_SUCCESS = "LISTING_CAT_SUCCESS";
export const LISTING_CAT_FAIL  = "LISTING_CAT_FAIL";


export const LISTING_SUBCAT_REQUEST = "LISTING_SUBCAT_REQUEST";
export const LISTING_SUBCAT_SUCCESS = "LISTING_SUBCAT_SUCCESS";
export const LISTING_SUBCAT_FAIL  = "LISTING_SUBCAT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";