export const ALL_OFFER_REQUEST = "ALL_STORE_REQUEST";
export const ALL_OFFER_SUCCESS = "ALL_STORE_SUCCESS";
export const ALL_OFFER_FAIL  = "ALL_STORE_FAIL";



export const LISTINGCAT_REQUEST = "LISTINGCAT_REQUEST";
export const LISTINGCAT_SUCCESS = "LISTINGCAT_SUCCESS";
export const LISTINGCAT_FAIL  = "LISTINGCAT_FAIL";


export const LISTINGSUBCAT_REQUEST = "LISTINGSUBCAT_REQUEST";
export const LISTINGSUBCAT_SUCCESS = "LISTINGSUBCAT_SUCCESS";
export const LISTINGSUBCAT_FAIL  = "LISTINGSUBCAT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";