export const STOREPAGE_REQUEST = "STOREPAGE_REQUEST";
export const STOREPAGE_SUCCESS = "STOREPAGE_SUCCESS";
export const STOREPAGE_FAIL  = "STOREPAGE_FAIL";

export const STOREPAGEOFFER_REQUEST = "STOREPAGEOFFER_REQUEST";
export const STOREPAGEOFFER_SUCCESS = "STOREPAGEOFFER_SUCCESS";
export const STOREPAGEOFFER_FAIL  = "STOREPAGEOFFER_FAIL";

export const STOREPAGEPRODUCT_REQUEST = "STOREPAGEOFFER_REQUEST";
export const STOREPAGEPRODUCT_SUCCESS = "STOREPAGEOFFER_SUCCESS";
export const STOREPAGEPRODUCT_FAIL  = "STOREPAGEOFFER_FAIL";

export const STOREPAGEABOUT_REQUEST = "STOREPAGEOFFER_REQUEST";
export const STOREPAGEABOUT_SUCCESS = "STOREPAGEOFFER_SUCCESS";
export const STOREPAGEABOUT_FAIL  = "STOREPAGEOFFER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";