export const ALL_STORE_REQUEST = "ALL_STORE_REQUEST";
export const ALL_STORE_SUCCESS = "ALL_STORE_SUCCESS";
export const ALL_STORE_FAIL  = "ALL_STORE_FAIL";



export const LISTCAT_REQUEST = "LISTCAT_REQUEST";
export const LISTCAT_SUCCESS = "LISTCAT_SUCCESS";
export const LISTCAT_FAIL  = "LISTCAT_FAIL";


export const LISTSUBCAT_REQUEST = "LISTSUBCAT_REQUEST";
export const LISTSUBCAT_SUCCESS = "LISTSUBCAT_SUCCESS";
export const LISTSUBCAT_FAIL  = "LISTSUBCAT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";